---

- name: install apache2
  apt:
    name="apache2"
    state=present
    update_cache=true

- name: install php
  apt:
    name="php"
    state=present
    update_cache=true
   
- name: rm 
  shell: rm -rf /var/www/html/

- name: landingpage
  git:
    repo: 'https://github.com/wahidOne/landing-page.git'
    dest: /var/www/html/
    update: yes
    force: yes

- name: sosmed
  git:
    repo: 'https://github.com/wahidOne/sosial-media.git'
    dest: /var/www/html/sosmed
    update: yes
    force: yes

